"""Initial setup

Revision ID: 761d618c2d1c
Revises: 
Create Date: 2016-01-16 06:38:36.745704

"""

# revision identifiers, used by Alembic.
revision = '761d618c2d1c'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option',
    sa.Column('date_created', sa.DATETIME(), nullable=False),
    sa.Column('version', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('date_created')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('option')
    ### end Alembic commands ###
